<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   dwi.atnorn    created date 06/05/2011 15:25
asset tester
Filename: uimstasset.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'master_asset';
	$__CONF['H']['PRIMARY_KEY'] 				= 'asset_id';
	$__CONF['H']['CREATEBY'] 					= 'asset_createby';
	$__CONF['H']['CREATEDATE'] 					= 'asset_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'asset_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'asset_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>