<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   dwi.atnorn    created date 06/05/2011 15:25
asset tester
Filename: uimstasset-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from master_asset where asset_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->asset_id = trim($rs->fields['asset_id']);
	$objh->asset_bookdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['asset_bookdate']));
	$objh->asset_name = trim($rs->fields['asset_name']);
	$objh->asset_descr = trim($rs->fields['asset_descr']);
	$objh->asset_notes = trim($rs->fields['asset_notes']);
	$objh->asset_merk = trim($rs->fields['asset_merk']);
	$objh->asset_type = trim($rs->fields['asset_type']);
	$objh->asset_sn = trim($rs->fields['asset_sn']);
	$objh->asset_location = trim($rs->fields['asset_location']);
	$objh->asset_pic = trim($rs->fields['asset_pic']);
	$objh->asset_isparent = trim($rs->fields['asset_isparent']);
	$objh->asset_owner_id = trim($rs->fields['asset_owner_id']);
	$objh->asset_ownership = trim($rs->fields['asset_ownership']);
	$objh->asset_movingtype = trim($rs->fields['asset_movingtype']);
	$objh->asset_status = trim($rs->fields['asset_status']);
	$objh->asset_iswritenoff = trim($rs->fields['asset_iswritenoff']);
	$objh->asset_createby = trim($rs->fields['asset_createby']);
	$objh->asset_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['asset_createdate']));
	$objh->asset_modifyby = trim($rs->fields['asset_modifyby']);
	$objh->asset_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['asset_modifydate']));
	$objh->asset_writenoffby = trim($rs->fields['asset_writenoffby']);
	$objh->asset_writenoffdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['asset_writenoffdate']));
	$objh->asset_writenoffref = trim($rs->fields['asset_writenoffref']);
	$objh->assetclass_id = trim($rs->fields['assetclass_id']);
	$objh->assetorder_id = trim($rs->fields['assetorder_id']);
	$objh->assetorder_line = (float) trim($rs->fields['assetorder_line']);
	$objh->assetrv_id = trim($rs->fields['assetrv_id']);
	$objh->assetrv_line = (float) trim($rs->fields['assetrv_line']);
	$objh->zone_id = trim($rs->fields['zone_id']);
	$objh->strukturunit_id = trim($rs->fields['strukturunit_id']);
	$objh->branch_id = trim($rs->fields['branch_id']);
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->rowid = trim($rs->fields['rowid']);


	/* Lookup data Header */
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>