<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 24/10/2011 13:15
Upload Opname
Filename: uitrnuploadopname-save_detilitem.php
*/


		$DETIL_NAME = "DetilItem";
		$arrDetilData = $__POSTDATA->D->{$DETIL_NAME};
 
		if (is_array($arrDetilData)) {
			for ($i=0; $i<count($arrDetilData); $i++) {
				unset($obj);
				$obj->item_id = $arrDetilData[$i]->item_id;
				$obj->item_name = $arrDetilData[$i]->item_name;
				$obj->rak = $arrDetilData[$i]->rak;
				$obj->barcode = $arrDetilData[$i]->barcode;
				$obj->article = $arrDetilData[$i]->article;
				$obj->material_id = $arrDetilData[$i]->material_id;
				$obj->material_name = $arrDetilData[$i]->material_name;
				$obj->color_id = $arrDetilData[$i]->color_id;
				$obj->color_name = $arrDetilData[$i]->color_name;
				$obj->size_id = $arrDetilData[$i]->size_id;
				$obj->size_name = $arrDetilData[$i]->size_name;
				$obj->group_id = $arrDetilData[$i]->group_id;
				$obj->group_name = $arrDetilData[$i]->group_name;
				$obj->subgroup_id = $arrDetilData[$i]->subgroup_id;
				$obj->subgroup_name = $arrDetilData[$i]->subgroup_name;
				$obj->item_qty = $arrDetilData[$i]->item_qty;
				
				$_MODIFIED = true; 
				require dirname(__FILE__).'/../../../../updatedefault-detil.inc.php';				
			}
		}


?>