<?
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 24/10/2011 13:15
Upload Opname
Filename: uitrnuploadopname-gridlistload.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}


	/* Default Criteria */
	/*
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_channel_id', 'channel_id', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " %s = '%s' ");
	*/
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_isPosted', 'opname_isposted', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_opname_id', 'opname_id',  " %s = '%s'");	

	
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM transaksi_opname WHERE $SQL_CRITERIA ORDER BY opname_id DESC";
} else {
	$sql = "SELECT * FROM transaksi_opname ORDER BY opname_id DESC";
}



$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);
	$obj->opname_id = trim($rs->fields['opname_id']);
	$obj->opname_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opname_date']));
	$obj->opname_descr = trim($rs->fields['opname_descr']);
	$obj->opname_filename = trim($rs->fields['opname_filename']);
	$obj->opnameproject_id = trim($rs->fields['opnameproject_id']);
	$obj->opname_createby = trim($rs->fields['opname_createby']);
	$obj->opname_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opname_createdate']));
	$obj->opname_modifyby = trim($rs->fields['opname_modifyby']);
	$obj->opname_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opname_modifydate']));
	$obj->opnameproject_id = trim($rs->fields['opnameproject_id']);
	
	
	$region_id = trim($rs->fields['region_id']);
	$SQLR = "SELECT region_name FROM master_region WHERE region_id = '$region_id'";
	$rsR = $conn->Execute($SQLR);
	$region_name = $rsR->fields['region_name'];
	$obj->region_name = $region_name;	
	$obj->region_id = $region_id;	
	
	$branch_id = trim($rs->fields['branch_id']);
	$SQLB = "SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
	$rsB = $conn->Execute($SQLB);
	$branch_name = $rsB->fields['branch_name'];
	$obj->branch_name = $branch_name;	
	$obj->branch_id = $branch_id;	
	
	$opnameproject_id = trim($rs->fields['opnameproject_id']);
	$SQLO = "SELECT opnameproject_descr FROM transaksi_opnameproject WHERE opnameproject_id = '$opnameproject_id'";
	$rsO = $conn->Execute($SQLO);
	$opnameproject_descr = $rsO->fields['opnameproject_descr'];
	$obj->opnameproject_descr = $opnameproject_descr;	
	$obj->opnameproject_id = $opnameproject_id;	
	$obj->opname_isposted = trim($rs->fields['opname_isposted']);		
	
	
	$obj->rowid = trim($rs->fields['rowid']);

	$data[] = $obj;
	$rs->MoveNext();
}



$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>