<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 24/10/2011 13:15
Upload Opname
Filename: uitrnuploadopname-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);

			$obj->opname_date = $__POSTDATA->H->opname_date;
			$obj->opname_descr = $__POSTDATA->H->opname_descr;

			$obj->opname_filename = $__POSTDATA->H->opname_filename;
			$obj->opnameproject_id = $__POSTDATA->H->opnameproject_id;
			$obj->opname_isposted = (float) $__POSTDATA->H->opname_isposted;

			$obj->opname_createby = $__POSTDATA->H->opname_createby;
			$obj->opname_createdate = $__POSTDATA->H->opname_createdate;
			$obj->opname_modifyby = $__POSTDATA->H->opname_modifyby;
			$obj->opname_modifydate = $__POSTDATA->H->opname_modifydate;
			$obj->region_id = $__POSTDATA->H->region_id;
			$obj->branch_id = $__POSTDATA->H->branch_id;
			
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
			function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;
			$channel_number = '05';	
 
			$sql  =  "DECLARE @id as varchar(50);";
			$sql .=  "EXEC cp_sequencer_opname 'OB', @id OUTPUT ";
			$rs   = $conn->Execute($sql);
			
			$id = $rs->fields['id'];

			if ($id) {
				return $id;

			} else {
				return $time();
			}
			
			
		}		

	

?>