<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 24/10/2011 13:15
Upload Opname
Filename: uitrnuploadopname-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from transaksi_opname where opname_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->opname_id = trim($rs->fields['opname_id']);
	$objh->opname_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opname_date']));
	$objh->opname_descr = trim($rs->fields['opname_descr']);
	
	$region_id = trim($rs->fields['region_id']);
	$SQLR = "SELECT region_name FROM master_region WHERE region_id = '$region_id'";
	$rsR = $conn->Execute($SQLR);
	$region_name = $rsR->fields['region_name'];
	$objh->region_name = $region_name;	
	$objh->region_id = $region_id;	
	
	$branch_id = trim($rs->fields['branch_id']);
	$SQLB = "SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
	$rsB = $conn->Execute($SQLB);
	$branch_name = $rsB->fields['branch_name'];
	$objh->branch_name = $branch_name;	
	$objh->branch_id = $branch_id;	
	
	$opnameproject_id = trim($rs->fields['opnameproject_id']);
	$SQLO = "SELECT opnameproject_descr FROM transaksi_opnameproject WHERE opnameproject_id = '$opnameproject_id'";
	$rsO = $conn->Execute($SQLO);
	$opnameproject_descr = $rsO->fields['opnameproject_descr'];
	$objh->opnameproject_descr = $opnameproject_descr;	
	$objh->opnameproject_id = $opnameproject_id;	

	
 
	$objh->opname_filename = trim($rs->fields['opname_filename']);
	$objh->opname_createby = trim($rs->fields['opname_createby']);
	$objh->opname_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opname_createdate']));
	$objh->opname_modifyby = trim($rs->fields['opname_modifyby']);
	$objh->opname_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opname_modifydate']));
	$objh->rowid = trim($rs->fields['rowid']);
	$objh->opname_isposted = 1*trim($rs->fields['opname_isposted']);



	$sql = "select  * from transaksi_opnamedetil where opname_id='$id'";
	$rs  = $conn->Execute($sql);
 
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->opname_id = trim($rs->fields['opname_id']);
		$obj->opnamedetil_line = (float) trim($rs->fields['opnamedetil_line']);
		$obj->item_id = trim($rs->fields['item_id']);
		$obj->item_name = trim($rs->fields['item_name']);
		//$obj->rak =  str_replace(array('"', "'"), array("", "",""),$rs->fields['rak']);
		$obj->rak =  trim($rs->fields['rak']);
		$obj->barcode = trim($rs->fields['barcode']);
		$obj->article = trim($rs->fields['article']);
		$obj->material_id = trim($rs->fields['material_id']);
		$obj->material_name = trim($rs->fields['material_name']);
		$obj->color_id = trim($rs->fields['color_id']);
		$obj->color_name = trim($rs->fields['color_name']);
		$obj->size_id = trim($rs->fields['size_id']);
		$obj->size_name = trim($rs->fields['size_name']);
		$obj->group_id = trim($rs->fields['group_id']);
		$obj->group_name = trim($rs->fields['group_name']);
		$obj->subgroup_id = trim($rs->fields['subgroup_id']);
		$obj->subgroup_name = trim($rs->fields['subgroup_name']);
		$obj->item_qty = (float) trim($rs->fields['item_qty']);
 
		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	$data[0]['D']['DetilItem'] = $arrdata;
	
	
	
	
	
	
	
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>