<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   luki.widodorn    created date 26/10/2011 10:14
Asset Request
Filename: uitrnAssetReq.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'transaksi_assetrequest';
	$__CONF['H']['PRIMARY_KEY'] 				= 'assetrequest_id';
	$__CONF['H']['CREATEBY'] 					= 'assetrequest_createby';
	$__CONF['H']['CREATEDATE'] 					= 'assetrequest_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'assetrequest_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'assetrequest_modifydate';

	$__CONF['D']['DetilItem']['TABLE_NAME']		= "transaksi_assetrequestdetil";
	$__CONF['D']['DetilItem']['PRIMARY_KEY1']	= "assetrequest_id";
	$__CONF['D']['DetilItem']['PRIMARY_KEY2']	= "assetrequestdetil_line";
	
	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>