<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   luki.widodorn    created date 26/10/2011 10:14
Asset Request
Filename: uitrnAssetReq-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from transaksi_assetrequest where assetrequest_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->assetrequest_id = trim($rs->fields['assetrequest_id']);
	$objh->assetrequest_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetrequest_date']));
	$objh->assetrequest_isdisabled = trim($rs->fields['assetrequest_isdisabled']);
	$objh->assetrequest_isposted = trim($rs->fields['assetrequest_isposted']);
	$objh->assetrequest_issent = 1*trim($rs->fields['assetrequest_issent']);
	$objh->assetrequest_duedate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetrequest_duedate']));
	$objh->assetrequest_descr = trim($rs->fields['assetrequest_descr']);
	$objh->assetrequest_dept = trim($rs->fields['assetrequest_dept']);
	$objh->assetrequest_createby = trim($rs->fields['assetrequest_createby']);
	$objh->assetrequest_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetrequest_createdate']));
	$objh->assetrequest_modifyby = trim($rs->fields['assetrequest_modifyby']);
	$objh->assetrequest_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetrequest_modifydate']));


	$region_id = trim($rs->fields['region_id']);
		$SQLB					= 	"SELECT region_name FROM master_region WHERE region_id = '$region_id'";
	    $rsB 					= 	$conn->execute($SQLB);
		$region_name 			= 	trim($rsB->fields['region_name']);
		$objh->region_id			=	$region_id;
		$objh->region_name		=	$region_name;

	$branch_id = trim($rs->fields['branch_id']);
		$SQLC					= 	"SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
	    $rsC 					= 	$conn->execute($SQLC);
		$branch_name 			= 	trim($rsC->fields['branch_name']);
		$objh->branch_id			=	$branch_id;
		$objh->branch_name		=	$branch_name;
		
	$strukturunit_id = trim($rs->fields['strukturunit_id']);
		$SQLD					= 	"SELECT strukturunit_name FROM master_strukturunit WHERE strukturunit_id = '$strukturunit_id'";
	    $rsD 					= 	$conn->execute($SQLD);
		$strukturunit_name 			= 	trim($rsD->fields['strukturunit_name']);
		$objh->strukturunit_id			=	$strukturunit_id;
		$objh->strukturunit_name			=	$strukturunit_name;					
		
	//$objh->owner_strukturunit_id = trim($rs->fields['owner_strukturunit_id']);
	
	$owner_strukturunit_id = trim($rs->fields['owner_strukturunit_id']);
		$SQLE					= 	"SELECT strukturunit_name FROM master_strukturunit WHERE strukturunit_id = '$owner_strukturunit_id'";
	    $rsE 					= 	$conn->execute($SQLE);
		$owner_strukturunit_name 			= 	trim($rsE->fields['strukturunit_name']);
		$objh->owner_strukturunit_id			=	$owner_strukturunit_id;
		$objh->owner_strukturunit_name			=	$owner_strukturunit_name;					
		
	
	$project_id = trim($rs->fields['project_id']);
		$SQLE					= 	"SELECT project_name FROM transaksi_project WHERE project_id = '$project_id'";
	    $rsE 					= 	$conn->execute($SQLE);
		$project_name 			= 	trim($rsE->fields['project_name']);
		$objh->project_id			=	$project_id;
		$objh->project_name			=	$project_name;					
	
	
	$objh->rowid = trim($rs->fields['rowid']);



	$sql = "select * from transaksi_assetrequestdetil where assetrequest_id='$id'";
	$rs  = $conn->Execute($sql);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->assetrequest_id = trim($rs->fields['assetrequest_id']);
		$obj->assetrequestdetil_line = (float) trim($rs->fields['assetrequestdetil_line']);
		$obj->assetclass_id = trim($rs->fields['assetclass_id']);
		$obj->assetclass_name = trim($rs->fields['assetclass_name']);
		$obj->assetrequestdetil_descr = trim($rs->fields['assetrequestdetil_descr']);
		$obj->assetrequestdetil_qty = (float) trim($rs->fields['assetrequestdetil_qty']);
	
	$region_id = trim($rs->fields['region_id']);
		$SQLB					= 	"SELECT region_name FROM master_region WHERE region_id = '$region_id'";
	    $rsB 					= 	$conn->execute($SQLB);
		$region_name 			= 	trim($rsB->fields['region_name']);
		$obj->region_id			=	$region_id;
		$obj->region_name		=	$region_name;

	$branch_id = trim($rs->fields['branch_id']);
		$SQLC					= 	"SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
	    $rsC 					= 	$conn->execute($SQLC);
		$branch_name 			= 	trim($rsC->fields['branch_name']);
		$obj->branch_id			=	$branch_id;
		$obj->branch_name		=	$branch_name;
		
	$strukturunit_id = trim($rs->fields['strukturunit_id']);
		$SQLD					= 	"SELECT strukturunit_name FROM master_strukturunit WHERE strukturunit_id = '$strukturunit_id'";
	    $rsD 					= 	$conn->execute($SQLD);
		$strukturunit_name 			= 	trim($rsD->fields['strukturunit_name']);
		$obj->strukturunit_id			=	$strukturunit_id;
		$obj->strukturunit_name			=	$strukturunit_name;					
	
	$owner_strukturunit_id = trim($rs->fields['owner_strukturunit_id']);
		$SQLE					= 	"SELECT strukturunit_name FROM master_strukturunit WHERE strukturunit_id = '$owner_strukturunit_id'";
	    $rsE 					= 	$conn->execute($SQLE);
		$owner_strukturunit_name 			= 	trim($rsE->fields['strukturunit_name']);
		$obj->owner_strukturunit_id			=	$owner_strukturunit_id;
		$obj->owner_strukturunit_name			=	$owner_strukturunit_name;					
			
	$project_id = trim($rs->fields['project_id']);
		$SQLE					= 	"SELECT project_name FROM transaksi_project WHERE project_id = '$project_id'";
	    $rsE 					= 	$conn->execute($SQLE);
		$project_name 			= 	trim($rsE->fields['project_name']);
		$obj->project_id			=	$project_id;
		$obj->project_name			=	$project_name;	
		
		$obj->assetrequestdetil_isclosed = trim($rs->fields['assetrequestdetil_isclosed']);
		$obj->rowid = trim($rs->fields['rowid']);

		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	$data[0]['D']['DetilItem'] = $arrdata;
	
	
	
	
	
	
	
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>