<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dhewe
    created date 05/08/2011 08:49
Project Management
Filename: uitrnpj.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'transaksi_project';
	$__CONF['H']['PRIMARY_KEY'] 				= 'project_id';
	$__CONF['H']['CREATEBY'] 					= 'project_createby';
	$__CONF['H']['CREATEDATE'] 					= 'project_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'project_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'project_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>