<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dhewe
    created date 05/08/2011 08:49
Project Management
Filename: uitrnpj-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from transaksi_project where project_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->project_id = trim($rs->fields['project_id']);
	$objh->project_rev = (float) trim($rs->fields['project_rev']);
	$objh->project_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['project_date']));
	$objh->project_datesetup = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['project_datesetup']));
	$objh->project_datedue = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['project_datedue']));
	$objh->project_name = trim($rs->fields['project_name']);
	$objh->project_descr = trim($rs->fields['project_descr']);
	$objh->project_location = trim($rs->fields['project_location']);
	$objh->project_isdisabled = trim($rs->fields['project_isdisabled']);
	$objh->project_isposted = trim($rs->fields['project_isposted']);
	$objh->project_isbudgedcommited = trim($rs->fields['project_isbudgedcommited']);
	$objh->project_isschedulecommited = trim($rs->fields['project_isschedulecommited']);
	$objh->project_iscompleted = trim($rs->fields['project_iscompleted']);
	$objh->project_createby = trim($rs->fields['project_createby']);
	$objh->project_createdate = trim($rs->fields['project_createdate']);
	$objh->project_modifyby = trim($rs->fields['project_modifyby']);
	$objh->project_modifydate = trim($rs->fields['project_modifydate']);
	$objh->projecttype_id = trim($rs->fields['projecttype_id']);
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->branch_id = trim($rs->fields['branch_id']);
	$objh->strukturunit_id = trim($rs->fields['strukturunit_id']);
	$objh->rowid = trim($rs->fields['rowid']);



	
	
	
	
	
	
	
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;





/* DETIL ====================================================================================================== */
$currline = 0;
$sql = "select *  from transaksi_assetrequest where project_id='$id' ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	$currline++;

	unset($obj);
	$obj->id = $id;
	$obj->line = $currline;
	$obj->purchaserequest_id = $rs->fields['assetrequest_id'];
	$obj->purchaserequest_date = $rs->fields['assetrequest_date'];
	$obj->purchaserequest_isdisabled = $rs->fields['assetrequest_isdisabled'];
	$obj->purchaserequest_isposted = $rs->fields['assetrequest_isposted'];
	$obj->purchaserequest_descr = $rs->fields['assetrequest_descr'];
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['PR'] = $arrdata;




/* DETIL DEFAULT ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>