<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dhewe
    created date 05/08/2011 08:49
Project Management
Filename: uitrnpj-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->project_rev = $__POSTDATA->H->project_rev;
			$obj->project_date = $__POSTDATA->H->project_date;
			$obj->project_datesetup = $__POSTDATA->H->project_datesetup;
			$obj->project_datedue = $__POSTDATA->H->project_datedue;
			$obj->project_name = $__POSTDATA->H->project_name;
			$obj->project_descr = $__POSTDATA->H->project_descr;
			$obj->project_location = $__POSTDATA->H->project_location;
			$obj->project_isdisabled = $__POSTDATA->H->project_isdisabled;
			$obj->project_isposted = $__POSTDATA->H->project_isposted;
			$obj->project_isbudgedcommited = $__POSTDATA->H->project_isbudgedcommited;
			$obj->project_isschedulecommited = $__POSTDATA->H->project_isschedulecommited;
			$obj->project_iscompleted = $__POSTDATA->H->project_iscompleted;
			$obj->project_createby = $__POSTDATA->H->project_createby;
			$obj->project_createdate = $__POSTDATA->H->project_createdate;
			$obj->project_modifyby = $__POSTDATA->H->project_modifyby;
			$obj->project_modifydate = $__POSTDATA->H->project_modifydate;
			$obj->projecttype_id = $__POSTDATA->H->projecttype_id;
			$obj->region_id = $__POSTDATA->H->region_id;
			$obj->branch_id = $__POSTDATA->H->branch_id;
			//$obj->strukturunit_id = $__POSTDATA->H->strukturunit_id;
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' => 'PJ',
				'region_id' => $__POSTDATA->H->region_id,
				'branch_id' =>$__POSTDATA->H->branch_id,
			);			
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
		
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];
			$region_id = $_ID_GENERATOR_ARGS['region_id'];
			$branch_id = $_ID_GENERATOR_ARGS['branch_id'];
			$channel_number = '05';
		
			$sql  =  "DECLARE @id as varchar(50);";
			$sql .=  "EXEC inv03_sequencer '$prefix', 'MGP', '$region_id', '$branch_id', @id OUTPUT ";
			$rs   = $conn->Execute($sql);
			$id = $rs->fields['id'];
			

			if ($id) {
				return $id;
			} else {
				return $prefix.time();
			}
		}		
	

?>