<?
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 23/03/2011 11:23
Program Untuk Mengentry Target
Filename: uitrntarget-gridlistload.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}


	/* Default Criteria */
	/*
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_channel_id', 'channel_id', " %s = '%s' ");

	*/
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_target_isposted', 'target_isposted', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_target_id', 'target_id', "refParser");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " %s = '%s' ");

	
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM transaksi_target WHERE $SQL_CRITERIA ORDER BY target_id DESC";
} else {
	$sql = "SELECT * FROM transaksi_target ORDER BY target_id DESC";
}



$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);
	$obj->target_id = trim($rs->fields['target_id']);
	$obj->target_isposted = (float) trim($rs->fields['target_isposted']);
	$obj->target_createby = trim($rs->fields['target_createby']);
	$obj->target_createdate = trim($rs->fields['target_createdate']);
	$obj->target_modifyby = trim($rs->fields['target_modifyby']);
	$obj->target_modifydate = trim($rs->fields['target_modifydate']);
	$obj->periode_id = trim($rs->fields['periode_id']);
	$obj->region_id = trim($rs->fields['region_id']);	
	$obj->rowid = trim($rs->fields['rowid']);

	$data[] = $obj;
	$rs->MoveNext();
}



$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>