<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 23/03/2011 11:23
Program Untuk Mengentry Target
Filename: uitrntarget-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->target_isposted = $__POSTDATA->H->target_isposted;
			$obj->target_createby = $__POSTDATA->H->target_createby;
			$obj->target_createdate = $__POSTDATA->H->target_createdate;
			$obj->target_modifyby = $__POSTDATA->H->target_modifyby;
			$obj->target_modifydate = $__POSTDATA->H->target_modifydate;
			//$obj->periode_id = ConvToPeriod($__POSTDATA->H->periode_id);
			$obj->periode_id = $__POSTDATA->H->periode_id;
		 
			$obj->region_id = $__POSTDATA->H->region_id;
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> 'TG',
				'region_id' => $__POSTDATA->H->region_id,
				'branch_id' =>'0000100'
			);
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];
			$region_id = $_ID_GENERATOR_ARGS['region_id'];
			$branch_id = $_ID_GENERATOR_ARGS['branch_id'];
			$channel_number = '05';
		
			$sql  =  "DECLARE @id as varchar(50);";
			$sql .=  "EXEC inv03_sequencer '$prefix', 'MGP', '$region_id', '$branch_id', @id OUTPUT ";
			$rs   = $conn->Execute($sql);
			$id = $rs->fields['id'];

			if ($id) {
				return $id;
			} else {
				return $prefix.time();				
			}

		}
	
		function ConvToPeriod($periode_id) {
			global $conn;		
			$ar = explode('/',$periode_id);
			
			$thn =  substr($ar[1],2,2) ;

			$bln = $ar[0];
			if (strlen($bln)==1)
			{
			 	$bln = '0'. $bln;
			 }
			
			return $thn . $bln;
			
		}
		
		

?>