 <?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 23/03/2011 11:23
Program Untuk Mengentry Target
Filename: uitrntarget.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'transaksi_target';
	$__CONF['H']['PRIMARY_KEY'] 				= 'target_id';
	$__CONF['H']['CREATEBY'] 					= 'target_createby';
	$__CONF['H']['CREATEDATE'] 					= 'target_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'target_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'target_modifydate';

	$__CONF['D']['DetilBranch']['TABLE_NAME']	= "transaksi_targetdetil";
	$__CONF['D']['DetilBranch']['PRIMARY_KEY1']	= "target_id";
	$__CONF['D']['DetilBranch']['PRIMARY_KEY2']	= "targetdetil_line";

	$__CONF['D']['DetilPerson']['TABLE_NAME']	= "transaksi_targetperson";
	$__CONF['D']['DetilPerson']['PRIMARY_KEY1']	= "target_id";
	$__CONF['D']['DetilPerson']['PRIMARY_KEY2']	= "targetperson_line";
		
	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>