
<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 23/03/2011 11:23
Program Untuk Mengentry Target
Filename: uitrntarget-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);

 
	$sql = "select * from transaksi_target where target_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->target_id = trim($rs->fields['target_id']);
	$objh->target_isposted = (float) trim($rs->fields['target_isposted']);
	$objh->target_createby = trim($rs->fields['target_createby']);
	$objh->target_createdate = trim($rs->fields['target_createdate']);
	$objh->target_modifyby = trim($rs->fields['target_modifyby']);
	$objh->target_modifydate = trim($rs->fields['target_modifydate']);
	
	

	/*$time_=date("d-m-Y H:i",strtotime ($datetime_fromSQL));
	

	$d = '1';
	if (strlen(substr(trim($rs->fields['periode_id']),3,2))==1)
	{
	 $m = '0' . substr(trim($rs->fields['periode_id']),3,2);	
	}
	else
	{
	 	 $m = substr(trim($rs->fields['periode_id']),3,2);	
	}
	  

	$y ='20' . substr(trim($rs->fields['periode_id']),0,2);
 
 
 
	$mk = mktime(0,0,0 ,$d, $m, $y);

print 	date('d-M-Y',$mk);
*/
	$objh->periode_id = trim($rs->fields['periode_id']);


	//print date('d-M-Y',$mk);
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->rowid = trim($rs->fields['rowid']);
 


	$sql = "select * from transaksi_targetdetil where target_id='$id'";
	$rs  = $conn->Execute($sql);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->target_id = trim($rs->fields['target_id']);
		$obj->targetdetil_line = (float) trim($rs->fields['targetdetil_line']);
		$obj->targetdetil_valuebudget = (float) trim($rs->fields['targetdetil_valuebudget']);
		$obj->targetdetil_valuetarget = (float) trim($rs->fields['targetdetil_valuetarget']);
		$obj->branch_id = trim($rs->fields['branch_id']);
		$branch_id = $obj->branch_id;
		
		
		$SQLBRANCH = "SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
		$rsBranch = $conn->execute($SQLBRANCH);
		
		$obj->branch_name = trim($rsBranch->fields['branch_name']);
		
		$obj->rowid = trim($rs->fields['rowid']);

		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	$data[0]['D']['DetilBranch'] = $arrdata;
	
	
	$sql = "select * from transaksi_targetperson where target_id='$id'";
	$rs  = $conn->Execute($sql);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->target_id = trim($rs->fields['target_id']);
		$obj->targetperson_line = (float) trim($rs->fields['targetperson_line']);
		$obj->targetperson_value = (float) trim($rs->fields['targetperson_value']);
		$obj->employee_id =  trim($rs->fields['employee_id']);
		$obj->employee_name = trim($rs->fields['employee_name']);
		$obj->branch_id = trim($rs->fields['branch_id']);
		$branch_id = $obj->branch_id;
		
		
		$SQLBRANCH = "SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
		$rsBranch = $conn->execute($SQLBRANCH);
		
		$obj->branch_name = trim($rsBranch->fields['branch_name']);
		
		$obj->rowid = trim($rs->fields['rowid']);

		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	$data[0]['D']['DetilPerson'] = $arrdata;
	
	
	
	
	
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>