<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 23/03/2011 11:23
Program Untuk Mengentry Target
Filename: uitrntarget-save_detilbranch.php
*/


		$DETIL_NAME = "DetilBranch";
		$arrDetilData = $__POSTDATA->D->{$DETIL_NAME};
		if (is_array($arrDetilData)) {
			for ($i=0; $i<count($arrDetilData); $i++) {
				unset($obj);
				$obj->targetdetil_valuebudget = $arrDetilData[$i]->targetdetil_valuebudget;
				$obj->targetdetil_valuetarget = $arrDetilData[$i]->targetdetil_valuetarget;
				$obj->branch_id = $arrDetilData[$i]->branch_id;
				
				$_MODIFIED = true; 
				require dirname(__FILE__).'/../../../../updatedefault-detil.inc.php';				
			}
		}


?>