<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   igun
    created date 23/03/2011 11:23
Program Untuk Mengentry Target
Filename: uitrntarget-save_detilbranch.php
*/


		$DETIL_NAME = "DetilPerson";
		$arrDetilData = $__POSTDATA->D->{$DETIL_NAME};
		if (is_array($arrDetilData)) {
			for ($i=0; $i<count($arrDetilData); $i++) {
				unset($obj);
				$obj->targetperson_value = $arrDetilData[$i]->targetperson_value;
				$obj->employee_id = $arrDetilData[$i]->employee_id;
				$obj->employee_name = $arrDetilData[$i]->employee_name;
				$obj->branch_id = $arrDetilData[$i]->branch_id;
				
				$_MODIFIED = true; 
				require dirname(__FILE__).'/../../../../updatedefault-detil.inc.php';				
			}
		}


?>