<?php
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'transaksi_heinvregister';
	$__CONF['H']['PRIMARY_KEY'] 				= 'heinvregister_id';
	$__CONF['H']['CREATEBY'] 					= 'heinvregister_createby';
	$__CONF['H']['CREATEDATE'] 					= 'heinvregister_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'heinvregister_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'heinvregister_modifydate';

	$__CONF['D']['DetilItem']['TABLE_NAME']		= "transaksi_heinvregisteritem";
	$__CONF['D']['DetilItem']['PRIMARY_KEY1']	= "heinvregister_id";
	$__CONF['D']['DetilItem']['PRIMARY_KEY2']	= "heinvregisteritem_line";
	
	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>