<?
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister-gridlistload.php
*/

if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}

	/* Default Criteria */
	/*
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_channel_id', 'channel_id', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " %s = '%s' ");
	*/

	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_heinvregister_id', 'heinvregister_id', "refParser");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_heinvregister_isposted', 'heinvregister_isposted', " {db_field}='{criteria_value}' ");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_heinvregister_isgenerated', 'heinvregister_isgenerated', " {db_field}={criteria_value} ");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " {db_field}='{criteria_value}' ");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_cbo_heinvregister_type', 'heinvregister_type', " {db_field}='{criteria_value}' ");	

	
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM transaksi_heinvregister WHERE $SQL_CRITERIA ORDER BY heinvregister_id DESC";
} else {
	$sql = "SELECT * FROM transaksi_heinvregister ORDER BY heinvregister_id DESC";
}




$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);
	$obj->heinvregister_id = trim($rs->fields['heinvregister_id']);
	$obj->heinvregister_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['heinvregister_date']));
	$obj->heinvregister_descr = trim($rs->fields['heinvregister_descr']);
	$obj->heinvregister_issizing = trim($rs->fields['heinvregister_issizing']);
	$obj->heinvregister_isposted = trim($rs->fields['heinvregister_isposted']);
	$obj->heinvregister_isgenerated = trim($rs->fields['heinvregister_isgenerated']);
	$obj->heinvregister_createby = trim($rs->fields['heinvregister_createby']);
	$obj->heinvregister_createdate = trim($rs->fields['heinvregister_createdate']);
	$obj->heinvregister_modifyby = trim($rs->fields['heinvregister_modifyby']);
	$obj->heinvregister_modifydate = trim($rs->fields['heinvregister_modifydate']);
	$obj->region_id = trim($rs->fields['region_id']);
	$obj->branch_id = trim($rs->fields['branch_id']);
	$obj->season_id = trim($rs->fields['season_id']);
	$obj->rekanan_id = trim($rs->fields['rekanan_id']);
	$obj->currency_id = trim($rs->fields['currency_id']);
	$obj->rowid = trim($rs->fields['rowid']);

	$data[] = $obj;
	$rs->MoveNext();
}



$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>