<?php
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister-save.php
*/

	if (!defined('__SERVICE__')) {
		die("access denied");
	}


	$__USERNAME	= $_SESSION["username"];
	$__ID		= $_POST["__ID"];
	$__JSONDATA	= $_POST['JSONDATA'];
	$__POSTDATA = json_decode(stripslashes($__JSONDATA));
	$__POSTDATA = $__POSTDATA[0];
	$__RESULT = array("");	
	$__RESULT[0]->__ID = $__ID;
	


	$sql = "select * from transaksi_heinvregister where heinvregister_id='$__ID'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->branch_id = trim($rs->fields['branch_id']);	
	$objh->season_id = trim($rs->fields['season_id']);
	$objh->heinvregister_issizing = trim($rs->fields['heinvregister_issizing']);


	 
	try {
		$conn->BeginTrans();
 
 		$sql = "UPDATE transaksi_heinvregister SET heinvregister_isgenerated='1' where heinvregister_id='$__ID'";
 		$conn->Execute($sql);
 
 		// insert to Log
		$SQL = "SELECT line=MAX(log_line) FROM ".$__CONF['D']['Log']['TABLE_NAME']." WHERE ".$__CONF['D']['Log']['PRIMARY_KEY1']." = '$__ID' ";
		$rs  = $conn->Execute($SQL);
		if (!$rs->recordCount()) {
			$LINE = 1;
		} else {
			$LINE = 1 + $rs->fields['line'];
		}
	
		unset($obj);		
		$obj->id			= $__ID;
		$obj->log_line		   = $LINE;
		$obj->log_action	   = "GENERATE";
		$obj->log_table		= "transaksi_heinvregister";
		$obj->log_descr		= "ClientIP:".$_POST['__MachineIP'].", ClientName:".$_POST['__MachineName'].", Rmt:".$_SERVER["REMOTE_ADDR"];
		$obj->log_lastvalue	= "";
		$obj->log_username	= $username;
		$SQL = SQLUTIL::SQL_InsertFromObject($__CONF['D']['Log']['TABLE_NAME'], $obj);
		$conn->Execute($SQL);
		 
 
		$success = true;
		$conn->CommitTrans();
	} catch (Exception $e) {
		$conn->RollbackTrans();
		$msg = $e->getMessage();
		$success = false;
		$dbErrors = new WebResultErrorObject("0x00000001", str_replace('"','',$msg));
	}


	$objResult = new WebResultObject("objResult");
	$objResult->totalCount = 1;
	$objResult->success = $success;
	$objResult->data =  $__RESULT;
	$objResult->errors = $dbErrors;
	if (!$dbErrors) unset($objResult->errors);
	
	print(stripslashes(json_encode($objResult)));
	
?>