<?php
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister-save.php
*/

	if (!defined('__SERVICE__')) {
		die("access denied");
	}


	$__USERNAME	= $_SESSION["username"];
	$__ID		= $_POST["__ID"];
    $__RV		= $_POST["__RV"];
	$__JSONDATA	= $_POST['JSONDATA'];
	$__POSTDATA = json_decode(stripslashes($__JSONDATA));
	$__POSTDATA = $__POSTDATA[0];
	$__RESULT = array("");	
	$__RESULT[0]->__ID = $__ID;
	

	if (empty($_POST) && isset($_SERVER['REQUEST_METHOD']) && strtolower($_SERVER['REQUEST_METHOD'])=='post') {
		$poidsMax = ini_get('post_max_size');
		$dbErrors = new WebResultErrorObject("0x00000001", "Data Overload, your data is too big, maximum allowed size here is $poidsMax");
		$objResult = new WebResultObject("objResult");
		$objResult->totalCount = 1;
		$objResult->success = false;
		$objResult->data = $__RESULT;
		$objResult->errors = $dbErrors;
		die(stripslashes(json_encode($objResult)));		
	}
	 
     
     
     
     
$register_id = $__ID;
$rv_id =$__RV;
     
     
     
     set_time_limit(60000);

try {

    

	$sql = "
					SET NOCOUNT ON;
	
					DECLARE @heinvregister_id AS varchar(30);
					SET @heinvregister_id = '$register_id'
					
					SELECT
						heinv_id,
						line =  10*ROW_NUMBER() OVER (ORDER BY heinv_id),
						C01 = isnull(SUM(isnull(C01,0)),0),
						C02 = isnull(SUM(isnull(C02,0)),0),
						C03 = isnull(SUM(isnull(C03,0)),0),
						C04 = isnull(SUM(isnull(C04,0)),0),
						C05 = isnull(SUM(isnull(C05,0)),0),
						C06 = isnull(SUM(isnull(C06,0)),0),
						C07 = isnull(SUM(isnull(C07,0)),0),
						C08 = isnull(SUM(isnull(C08,0)),0),
						C09 = isnull(SUM(isnull(C09,0)),0),
						C10 = isnull(SUM(isnull(C10,0)),0),
						C11 = isnull(SUM(isnull(C11,0)),0),
						C12 = isnull(SUM(isnull(C12,0)),0),
						C13 = isnull(SUM(isnull(C13,0)),0),
						C14 = isnull(SUM(isnull(C14,0)),0),
						C15 = isnull(SUM(isnull(C15,0)),0),
						C16 = isnull(SUM(isnull(C16,0)),0),
						C17 = isnull(SUM(isnull(C17,0)),0),
						C18 = isnull(SUM(isnull(C18,0)),0),
						C19 = isnull(SUM(isnull(C19,0)),0),
						C20 = isnull(SUM(isnull(C20,0)),0),
						C21 = isnull(SUM(isnull(C21,0)),0),
						C22 = isnull(SUM(isnull(C22,0)),0),
						C23 = isnull(SUM(isnull(C23,0)),0),
						C24 = isnull(SUM(isnull(C24,0)),0),
						C25 = isnull(SUM(isnull(C25,0)),0)
					FROM (
						select 
						A.heinv_id, 
						A.heinv_barcode, colname='C'+B.heinvitem_colnum, qty=A.C00
						from transaksi_heinvregisteritem A left join master_heinvitem B 
						on A.heinv_id=B.heinv_id AND A.heinv_barcode=B.heinvitem_barcode
						where heinvregister_id = @heinvregister_id
					) AS P
					PIVOT
					(SUM(qty) for colname IN (C01,C02,C03,C04,C05,C06,C07,C08,C09,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25)) AS PIV
					GROUP BY heinv_id
				";		






				$rsI  = $conn->Execute($sql);
				$seq = 0;
			 
				while (!$rsI->EOF) {
					$seq++; 
				
					unset($obj);
					$obj->hemoving_id = $rv_id;
					$obj->hemovingdetil_line = $rsI->fields['line'];
					
					$obj->heinv_id 	= $rsI->fields['heinv_id'];
					$sql = "SELECT * FROM master_heinv WHERE heinv_id='".$obj->heinv_id."'";
					$rsN = $conn->Execute($sql);
					
					$obj->heinv_art = $rsN->fields['heinv_art'];
					$obj->heinv_mat = $rsN->fields['heinv_mat'];
					$obj->heinv_col = $rsN->fields['heinv_col'];
					$obj->heinv_name = $rsN->fields['heinv_name'];

					$obj->heinv_price = 0;
					$obj->heinv_disc = 0;
					
					$obj->heinv_box = '';
					$obj->heinv_invoiceqty = 0;
					$obj->heinv_invoiceid = '';
					$obj->ref_id = '';
					$obj->ref_line = 0;

					$obj->A01		= $rsI->fields['C01'];
					$obj->A02		= $rsI->fields['C02'];
					$obj->A03		= $rsI->fields['C03'];
					$obj->A04		= $rsI->fields['C04'];
					$obj->A05		= $rsI->fields['C05'];
					$obj->A06		= $rsI->fields['C06'];
					$obj->A07		= $rsI->fields['C07'];
					$obj->A08		= $rsI->fields['C08'];
					$obj->A09		= $rsI->fields['C09'];
					$obj->A10		= $rsI->fields['C10'];
					$obj->A11		= $rsI->fields['C11'];
					$obj->A12		= $rsI->fields['C12'];
					$obj->A13		= $rsI->fields['C13'];
					$obj->A14		= $rsI->fields['C14'];
					$obj->A15		= $rsI->fields['C15'];
					$obj->A16		= $rsI->fields['C16'];
					$obj->A17		= $rsI->fields['C17'];
					$obj->A18		= $rsI->fields['C18'];
					$obj->A19		= $rsI->fields['C19'];
					$obj->A20		= $rsI->fields['C20'];
					$obj->A21		= $rsI->fields['C21'];
					$obj->A22		= $rsI->fields['C22'];
					$obj->A23		= $rsI->fields['C23'];
					$obj->A24		= $rsI->fields['C24'];
					$obj->A25		= $rsI->fields['C25'];
					
					$obj->B01		= $rsI->fields['C01'];
					$obj->B02		= $rsI->fields['C02'];
					$obj->B03		= $rsI->fields['C03'];
					$obj->B04		= $rsI->fields['C04'];
					$obj->B05		= $rsI->fields['C05'];
					$obj->B06		= $rsI->fields['C06'];
					$obj->B07		= $rsI->fields['C07'];
					$obj->B08		= $rsI->fields['C08'];
					$obj->B09		= $rsI->fields['C09'];
					$obj->B10		= $rsI->fields['C10'];
					$obj->B11		= $rsI->fields['C11'];
					$obj->B12		= $rsI->fields['C12'];
					$obj->B13		= $rsI->fields['C13'];
					$obj->B14		= $rsI->fields['C14'];
					$obj->B15		= $rsI->fields['C15'];
					$obj->B16		= $rsI->fields['C16'];
					$obj->B17		= $rsI->fields['C17'];
					$obj->B18		= $rsI->fields['C18'];
					$obj->B19		= $rsI->fields['C19'];
					$obj->B20		= $rsI->fields['C20'];
					$obj->B21		= $rsI->fields['C21'];
					$obj->B22		= $rsI->fields['C22'];
					$obj->B23		= $rsI->fields['C23'];
					$obj->B24		= $rsI->fields['C24'];
					$obj->B25		= $rsI->fields['C25'];					

					$obj->C01		= $rsI->fields['C01'];
					$obj->C02		= $rsI->fields['C02'];
					$obj->C03		= $rsI->fields['C03'];
					$obj->C04		= $rsI->fields['C04'];
					$obj->C05		= $rsI->fields['C05'];
					$obj->C06		= $rsI->fields['C06'];
					$obj->C07		= $rsI->fields['C07'];
					$obj->C08		= $rsI->fields['C08'];
					$obj->C09		= $rsI->fields['C09'];
					$obj->C10		= $rsI->fields['C10'];
					$obj->C11		= $rsI->fields['C11'];
					$obj->C12		= $rsI->fields['C12'];
					$obj->C13		= $rsI->fields['C13'];
					$obj->C14		= $rsI->fields['C14'];
					$obj->C15		= $rsI->fields['C15'];
					$obj->C16		= $rsI->fields['C16'];
					$obj->C17		= $rsI->fields['C17'];
					$obj->C18		= $rsI->fields['C18'];
					$obj->C19		= $rsI->fields['C19'];
					$obj->C20		= $rsI->fields['C20'];
					$obj->C21		= $rsI->fields['C21'];
					$obj->C22		= $rsI->fields['C22'];
					$obj->C23		= $rsI->fields['C23'];
					$obj->C24		= $rsI->fields['C24'];
					$obj->C25		= $rsI->fields['C25'];
				
					$SQL = SQLUTIL::SQL_InsertFromObject("transaksi_hemovingdetil", $obj);
				 
					$conn->Execute($SQL);
				
					$rsI->MoveNext();
				}
	 
}  catch (exception $e) {
	print "--".$e->GetMessage();	
}

	 	

 

	$objResult = new WebResultObject("objResult");
	$objResult->totalCount = 1;
	$objResult->success = true;
	$objResult->data =  $__RESULT;
	$objResult->errors = $dbErrors;
	if (!$dbErrors) unset($objResult->errors);
	
	print(stripslashes(json_encode($objResult)));
	
?>