<?php
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister-save_header.php
*/


		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->heinvregister_date = $__POSTDATA->H->heinvregister_date;
			$obj->heinvregister_descr = $__POSTDATA->H->heinvregister_descr;
			$obj->heinvregister_type = $__POSTDATA->H->heinvregister_type;
			$obj->heinvregister_issizing = $__POSTDATA->H->heinvregister_issizing;
			$obj->heinvregister_isposted = $__POSTDATA->H->heinvregister_isposted;
			$obj->heinvregister_isgenerated = $__POSTDATA->H->heinvregister_isgenerated;
			$obj->heinvregister_isseasonupdate = $__POSTDATA->H->heinvregister_isseasonupdate;
			$obj->region_id = $__POSTDATA->H->region_id;
			$obj->branch_id = $__POSTDATA->H->branch_id;
			$obj->season_id = $__POSTDATA->H->season_id;
			$obj->rekanan_id = $__POSTDATA->H->rekanan_id;
			$obj->currency_id = $__POSTDATA->H->currency_id;
		
		
			if ($obj->heinvregister_issizing==0) {
				throw new Exception("per 2017 Oktober, Register Item harus sizing!"); 
			}
		
			if ($obj->season_id=='000') {
				throw new Exception("per 2017 Oktober, Tidak boleh register season '000'!"); 
			}
					
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
		
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];

			if ($id) {
				return $id;
			} else {
				return $prefix.time();
			}
		}		
	

?>