<?php
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from transaksi_heinvregister where heinvregister_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->heinvregister_id = trim($rs->fields['heinvregister_id']);
	$objh->heinvregister_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['heinvregister_date']));

	$objh->heinvregister_type = trim($rs->fields['heinvregister_type']);
	if ($objh->heinvregister_type=='') {
		$objh->heinvregister_type='0';
	}

	$objh->heinvregister_descr = trim($rs->fields['heinvregister_descr']);
	$objh->heinvregister_issizing = trim($rs->fields['heinvregister_issizing']);
	$objh->heinvregister_isposted = trim($rs->fields['heinvregister_isposted']);
	$objh->heinvregister_isgenerated = trim($rs->fields['heinvregister_isgenerated']);
	$objh->heinvregister_isseasonupdate = trim($rs->fields['heinvregister_isseasonupdate']);
	$objh->heinvregister_createby = trim($rs->fields['heinvregister_createby']);
	$objh->heinvregister_createdate = trim($rs->fields['heinvregister_createdate']);
	$objh->heinvregister_modifyby = trim($rs->fields['heinvregister_modifyby']);
	$objh->heinvregister_modifydate = trim($rs->fields['heinvregister_modifydate']);
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->branch_id = trim($rs->fields['branch_id']);
	$objh->season_id = trim($rs->fields['season_id']);
	$objh->season_name = trim(SQLUTIL::GetRsFromTableById("master_season", "season_id", $objh->season_id, $conn)->fields['season_name']);
	$objh->rekanan_id = trim($rs->fields['rekanan_id']);
	$objh->rekanan_name = trim(SQLUTIL::GetRsFromTableById("master_rekanan", "rekanan_id", $objh->rekanan_id, $conn)->fields['rekanan_name']);
	$objh->currency_id = trim($rs->fields['currency_id']);
	$objh->rowid = trim($rs->fields['rowid']);


	

	$sql = "select * from transaksi_heinvregisteritem where heinvregister_id='$id'";
	$rs  = $conn->Execute($sql);
	$totaldetilrows = $rs->recordCount();

	/*
	$sql = "select * from transaksi_heinvregisteritem where heinvregister_id='$id' order by heinvregisteritem_line";
	$rs  = $conn->SelectLimit($sql, 100);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->heinvregister_id = (string) trim($rs->fields['heinvregister_id']);
		$obj->heinvregisteritem_line = (float) trim($rs->fields['heinvregisteritem_line']);
		$obj->heinv_art = (string) trim($rs->fields['heinv_art']);
		$obj->heinv_mat = (string) trim($rs->fields['heinv_mat']);
		$obj->heinv_col = (string) trim($rs->fields['heinv_col']);
		$obj->heinv_size = (string) trim($rs->fields['heinv_size']);
		$obj->heinv_name = (string) trim($rs->fields['heinv_name']);
		$obj->heinv_descr = (string) trim($rs->fields['heinv_descr']);
		$obj->heinv_gtype = (string) trim($rs->fields['heinv_gtype']);
		$obj->heinv_produk = (string) trim($rs->fields['heinv_produk']);
		$obj->heinv_bahan = (string) trim($rs->fields['heinv_bahan']);
		$obj->heinv_pemeliharaan = (string) trim($rs->fields['heinv_pemeliharaan']);
		$obj->heinv_logo = (string) trim($rs->fields['heinv_logo']);
		$obj->heinv_dibuatdi = (string) trim($rs->fields['heinv_dibuatdi']);
		$obj->heinv_other1 = (string) trim($rs->fields['heinv_other1']);
		$obj->heinv_other2 = (string) trim($rs->fields['heinv_other2']);
		$obj->heinv_other3 = (string) trim($rs->fields['heinv_other3']);
		$obj->heinv_other4 = (string) trim($rs->fields['heinv_other4']);
		$obj->heinv_other5 = (string) trim($rs->fields['heinv_other5']);
		$obj->heinv_price = (float) trim($rs->fields['heinv_price']);
		$obj->heinvctg_id = (string) trim($rs->fields['heinvctg_id']);
		$obj->region_id = (string) trim($objh->region_id);
		$obj->branch_id = (string) trim($rs->fields['branch_id']);
		$obj->branch_name = (string) SQLUTIL::GetRsFromTableById("master_branch", "branch_id", $obj->branch_id, $conn)->fields['branch_name'];
		$obj->heinv_id = (string) (trim($rs->fields['heinv_id']) ? trim($rs->fields['heinv_id']) : SQLUTIL::GetRsHeinvFromTableByKey($obj->heinv_art, $obj->heinv_mat, $obj->heinv_col, $obj->region_id, $conn)->fields['heinv_id']);

		if ($obj->heinv_id) {
			// kalau ada heinv_id nya, data2 nya di ovverride dari heinv_id nya 
			$sql = " select heinvctg_id, region_id from master_heinv where heinv_id='".$obj->heinv_id."' ";
			$rsI = $conn->Execute($sql);
			$obj->heinvctg_id = (string) trim($rsI->fields['heinvctg_id']);
			$obj->region_id   = (string) trim($rsI->fields['region_id']);
		} 

		$sql = "select heinvctg_name, heinvctg_sizetag, heinvgro_id from master_heinvctg where heinvctg_id='$obj->heinvctg_id' and region_id='$obj->region_id' ";
		$rsI = $conn->Execute($sql);
		$obj->heinvctg_name = (string) trim($rsI->fields['heinvctg_name']);						
		$obj->heinvctg_sizetag = (string) trim($rsI->fields['heinvctg_sizetag']);						
		$obj->heinvgro_id = (string) trim($rsI->fields['heinvgro_id']);	
		
		$sql = "select heinvgro_name from master_heinvgro where heinvgro_id='$obj->heinvgro_id' and region_id='$obj->region_id' ";
		$rsI = $conn->Execute($sql);
		$obj->heinvgro_name = (string) trim($rsI->fields['heinvgro_name']);						


		$obj->C00 = (float) trim($rs->fields['C00']);
		$obj->C01 = (float) trim($rs->fields['C01']);
		$obj->C02 = (float) trim($rs->fields['C02']);
		$obj->C03 = (float) trim($rs->fields['C03']);
		$obj->C04 = (float) trim($rs->fields['C04']);
		$obj->C05 = (float) trim($rs->fields['C05']);
		$obj->C06 = (float) trim($rs->fields['C06']);
		$obj->C07 = (float) trim($rs->fields['C07']);
		$obj->C08 = (float) trim($rs->fields['C08']);
		$obj->C09 = (float) trim($rs->fields['C09']);
		$obj->C10 = (float) trim($rs->fields['C10']);
		$obj->C11 = (float) trim($rs->fields['C11']);
		$obj->C12 = (float) trim($rs->fields['C12']);
		$obj->C13 = (float) trim($rs->fields['C13']);
		$obj->C14 = (float) trim($rs->fields['C14']);
		$obj->C15 = (float) trim($rs->fields['C15']);
		$obj->C16 = (float) trim($rs->fields['C16']);
		$obj->C17 = (float) trim($rs->fields['C17']);
		$obj->C18 = (float) trim($rs->fields['C18']);
		$obj->C19 = (float) trim($rs->fields['C19']);
		$obj->C20 = (float) trim($rs->fields['C20']);
		$obj->C21 = (float) trim($rs->fields['C21']);
		$obj->C22 = (float) trim($rs->fields['C22']);
		$obj->C23 = (float) trim($rs->fields['C23']);
		$obj->C24 = (float) trim($rs->fields['C24']);
		$obj->C25 = (float) trim($rs->fields['C25']);
		$obj->rowid = (string) trim($rs->fields['rowid']);
		
		
		//validasi item
		if ($objh->heinvregister_issizing) {
			$obj->err = 99;
		} else {
			if (!$obj->heinvgro_id || !$obj->heinvgro_name) {
				$obj->err = 1;
			} else {
				$obj->err = 0;
			}
		}
		

		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	*/
	
	$data[0]['D']['DetilItem'] = array(); //$arrdata;
	
	
	
	
	
	
	
	

	/* Lookup data Header */
	$objh->totaldetilrows = (float) $totaldetilrows;
	
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>