<?php
/*
Generated by TransBrowser Generator
Created by dhewe, 21/03/2011 15:55
Program untuk registrasi item
Filename: uitrnheinvregister-save.php
*/

	if (!defined('__SERVICE__')) {
		die("access denied");
	}


	$__USERNAME	= $_SESSION["username"];
	$__ID		= $_POST["__ID"];
	$__JSONDATA	= $_POST['JSONDATA'];
	$__POSTDATA = json_decode(stripslashes($__JSONDATA));
	$__POSTDATA = $__POSTDATA[0];
	$__RESULT = array("");	
	$__RESULT[0]->__ID = $__ID;
	

	if (empty($_POST) && isset($_SERVER['REQUEST_METHOD']) && strtolower($_SERVER['REQUEST_METHOD'])=='post') {
		$poidsMax = ini_get('post_max_size');
		$dbErrors = new WebResultErrorObject("0x00000001", "Data Overload, your data is too big, maximum allowed size here is $poidsMax");
		$objResult = new WebResultObject("objResult");
		$objResult->totalCount = 1;
		$objResult->success = false;
		$objResult->data = $__RESULT;
		$objResult->errors = $dbErrors;
		die(stripslashes(json_encode($objResult)));		
	}
	 
	try {
		$conn->BeginTrans();
 
 		$arrDetilData = $__POSTDATA->DetilItem;
		if (is_array($arrDetilData)) {
			for ($i=0; $i<count($arrDetilData); $i++) {
				unset($obj);	

				$obj->heinvregister_id 		= (string) $__ID;
				$obj->heinvregisteritem_line= (int) SQLUTIL::Normal($arrDetilData[$i]->heinvregisteritem_line);

				$obj->heinv_art 		= (string) SQLUTIL::Normal($arrDetilData[$i]->heinv_art);
				$obj->heinv_mat 		= (string) SQLUTIL::Normal($arrDetilData[$i]->heinv_mat);
				$obj->heinv_col 		= (string) SQLUTIL::Normal($arrDetilData[$i]->heinv_col);
				$obj->heinv_size 		= (string) SQLUTIL::Normal($arrDetilData[$i]->heinv_size); 
				
				if(!trim($obj->heinv_size))
				{
					$obj->heinv_size = "N/A"; 
				}
				$obj->heinv_barcode 	= (string) SQLUTIL::Normal($arrDetilData[$i]->heinv_barcode); 
				$obj->heinv_name 		= substr((string) $arrDetilData[$i]->heinv_name,0,40);
				$obj->heinv_descr 		= substr((string) $arrDetilData[$i]->heinv_descr,0,50);
				$obj->heinv_gtype 		= $arrDetilData[$i]->heinv_gtype;
				$obj->heinv_produk 		= $arrDetilData[$i]->heinv_produk;
				$obj->heinv_bahan 		= (string) substr(SQLUTIL::Normal($arrDetilData[$i]->heinv_bahan),0,69);
				$obj->heinv_pemeliharaan= (string) substr(SQLUTIL::Normal($arrDetilData[$i]->heinv_pemeliharaan),0,99);
				$obj->heinv_logo 		= $arrDetilData[$i]->heinv_logo;
				$obj->heinv_dibuatdi 	= $arrDetilData[$i]->heinv_dibuatdi;
				// $obj->heinv_other1 		= $arrDetilData[$i]->heinv_other1;
				// $obj->heinv_other2 		= $arrDetilData[$i]->heinv_other2;
				// $obj->heinv_other3 		= $arrDetilData[$i]->heinv_other3;
				// $obj->heinv_other4 		= $arrDetilData[$i]->heinv_other4;
				// $obj->heinv_other5 		= $arrDetilData[$i]->heinv_other5;
				$obj->heinv_other2 		= substr((string) trim($arrDetilData[$i]->heinv_pline),0,50);
				$obj->heinv_other3 		= substr((string) trim($arrDetilData[$i]->heinv_fit),0,50);
				$obj->heinv_other4 		= substr((string) trim($arrDetilData[$i]->heinv_pgroup),0,50);
				$obj->heinv_other5 		= substr((string) trim($arrDetilData[$i]->heinv_pcategory),0,50);
				$obj->heinv_other6 		= substr((string) trim($arrDetilData[$i]->heinv_colordescr),0,30);
				$obj->heinv_other7 		= substr((string) trim($arrDetilData[$i]->heinv_gender),0,1);

				$obj->heinv_hscode_ina 	    = substr((string) trim($arrDetilData[$i]->heinv_hscode_ina),0,50);
				$obj->heinv_hscode_ship 		= substr((string) trim($arrDetilData[$i]->heinv_hscode_ship),0,50);
				$obj->heinv_plbname 		= substr((string) trim($arrDetilData[$i]->heinv_plbname),0,100);


				$obj->heinv_price 		= $arrDetilData[$i]->heinv_price;
				//$obj->heinvgro_id 		= $arrDetilData[$i]->heinvgro_id;
				$obj->heinvctg_id 		= $arrDetilData[$i]->heinvctg_id;
				//$obj->heinvctg_sizetag  = $arrDetilData[$i]->heinvctg_sizetag;
				$obj->branch_id 		= (string) SQLUTIL::Normal($arrDetilData[$i]->branch_id);				
				$obj->C00 = $arrDetilData[$i]->C00;
				$obj->C01 = $arrDetilData[$i]->C01;
				$obj->C02 = $arrDetilData[$i]->C02;
				$obj->C03 = $arrDetilData[$i]->C03;
				$obj->C04 = $arrDetilData[$i]->C04;
				$obj->C05 = $arrDetilData[$i]->C05;
				$obj->C06 = $arrDetilData[$i]->C06;
				$obj->C07 = $arrDetilData[$i]->C07;
				$obj->C08 = $arrDetilData[$i]->C08;
				$obj->C09 = $arrDetilData[$i]->C09;
				$obj->C10 = $arrDetilData[$i]->C10;
				$obj->C11 = $arrDetilData[$i]->C11;
				$obj->C12 = $arrDetilData[$i]->C12;
				$obj->C13 = $arrDetilData[$i]->C13;
				$obj->C14 = $arrDetilData[$i]->C14;
				$obj->C15 = $arrDetilData[$i]->C15;
				$obj->C16 = $arrDetilData[$i]->C16;
				$obj->C17 = $arrDetilData[$i]->C17;
				$obj->C18 = $arrDetilData[$i]->C18;
				$obj->C19 = $arrDetilData[$i]->C19;
				$obj->C20 = $arrDetilData[$i]->C20;
				$obj->C21 = $arrDetilData[$i]->C21;
				$obj->C22 = $arrDetilData[$i]->C22;
				$obj->C23 = $arrDetilData[$i]->C23;
				$obj->C24 = $arrDetilData[$i]->C24;
				$obj->C25 = $arrDetilData[$i]->C25;


				require dirname(__FILE__).'/uitrnheinvregister-save_detilitem_lookup.php';


				$SQL = SQLUTIL::SQL_InsertFromObject("transaksi_heinvregisteritem", $obj);
				$conn->Execute($SQL);



			}		
		} 		
 		
		
		$success = true;
		$conn->CommitTrans();
	} catch (Exception $e) {
		$conn->RollbackTrans();
		$msg = $e->getMessage();
		$success = false;
		$dbErrors = new WebResultErrorObject("0x00000001", str_replace('"','',$msg));
	}


	$objResult = new WebResultObject("objResult");
	$objResult->totalCount = 1;
	$objResult->success = $success;
	$objResult->data =  $__RESULT;
	$objResult->errors = $dbErrors;
	if (!$dbErrors) unset($objResult->errors);
	
	print(stripslashes(json_encode($objResult)));
	
?>