 <?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   igunrn    created date 08/11/2011 13:21
Opname Project
Filename: uitrnopnameproject-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from transaksi_opnameproject where opnameproject_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->opnameproject_id = trim($rs->fields['opnameproject_id']);
	$objh->opnameproject_startdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opnameproject_startdate']));
	$objh->opnameproject_enddate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['opnameproject_enddate']));
	$objh->opnameproject_isdisabled = trim($rs->fields['opnameproject_isdisabled']);
	$objh->opnameproject_descr = trim($rs->fields['opnameproject_descr']);
	$objh->opnameproject_createby = trim($rs->fields['opnameproject_createby']);
	$objh->opnameproject_createdate = trim($rs->fields['opnameproject_createdate']);
	$objh->opnameproject_modifyby = trim($rs->fields['opnameproject_modifyby']);
	$objh->opnameproject_modifydate = trim($rs->fields['opnameproject_modifydate']);
	$objh->rowid = trim($rs->fields['rowid']);
	$objh->opnameproject_isposted = trim($rs->fields['opnameproject_isposted']);
	$objh->opnameproject_isgenerated = trim($rs->fields['opnameproject_isgenerated']);

	
	$region_id = trim($rs->fields['region_id']);
	$SQLR = "SELECT region_name FROM master_region WHERE region_id = '$region_id'";
	$rsR = $conn->execute($SQLR);
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->region_name = trim($rsR->fields['region_name']);
	


	$sql = "select * from transaksi_opnameprojectmoving where opnameprojectmoving_id='$id'";
	$rs  = $conn->Execute($sql);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->opnameprojectmoving_id = trim($rs->fields['opnameprojectmoving_id']);
		$obj->opnameprojectmoving_line = (float) trim($rs->fields['opnameprojectmoving_line']);
		$obj->hemoving_id = trim($rs->fields['hemoving_id']);

		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	$data[0]['D']['DetilMoving'] = $arrdata;
	


	$sql = "select opname_id,opname_date,opname_descr from transaksi_opname where opnameproject_id='$id' and opname_isposted=1";
	$rs  = $conn->Execute($sql);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->opname_id = trim($rs->fields['opname_id']);
		$obj->opname_date =   trim($rs->fields['opname_date']);
		$obj->opname_descr = trim($rs->fields['opname_descr']);
		$arrdata[] = $obj;
		
		$rs->MoveNext();
	}
	$data[0]['D']['DetilOpname'] = $arrdata;

	
		$arrdata = array();
		unset($obj);
		$obj->hemoving_id 			= "";
		$obj->hemovingdetil_line 	= 0;
		$obj->heinvitem_colnum 	= "";
		$obj->heinv_id 	= "";
		$obj->heinv_box 	= "";
		$obj->qty_B 	= 0;
		$obj->qty_C 	= 0;
		$obj->rowid 	= "";
	 
		$arrdata[] = $obj;
 
		$data[0]['D']['DetilShortage'] = $arrdata;	
	
	
		$arrdata = array();
		unset($obj);
		$obj->heinv_id 			= "";
		$obj->heinv_art 		= "";
		$obj->heinv_mat 		= "";
		$obj->heinv_col 		= "";
		$obj->heinv_name 		= "";
		$obj->heinvitem_size	= "";
		$obj->heinvitem_colnum	= "";
		$obj->heinv_box	= "";		
		$obj->qty				= 0;
		$obj->qty_reserved 		= 0;
		$obj->selisih 			= 0;

		$obj->rowid 			= "";
	 
		$arrdata[] = $obj;
 
		$data[0]['D']['DetilExcess'] = $arrdata;	
	
	 
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;

 


/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>