<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   igunrn    created date 08/11/2011 13:21
Opname Project
Filename: uitrnopnameproject-save_detilmoving.php
*/


		$DETIL_NAME = "DetilMoving";
		$arrDetilData = $__POSTDATA->D->{$DETIL_NAME};
		if (is_array($arrDetilData)) {
			for ($i=0; $i<count($arrDetilData); $i++) {
				unset($obj);
				$obj->hemoving_id = $arrDetilData[$i]->hemoving_id;
				
				$_MODIFIED = true; 
				require dirname(__FILE__).'/../../../../updatedefault-detil.inc.php';				
			}
		}


?>