<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   igunrn    created date 08/11/2011 13:21
Opname Project
Filename: uitrnopnameproject.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'transaksi_opnameproject';
	$__CONF['H']['PRIMARY_KEY'] 				= 'opnameproject_id';
	$__CONF['H']['CREATEBY'] 					= 'opnameproject_createby';
	$__CONF['H']['CREATEDATE'] 					= 'opnameproject_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'opnameproject_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'opnameproject_modifydate';

	$__CONF['D']['DetilMoving']['TABLE_NAME']		= "transaksi_opnameprojectmoving";
	$__CONF['D']['DetilMoving']['PRIMARY_KEY1']	= "opnameprojectmoving_id";
	$__CONF['D']['DetilMoving']['PRIMARY_KEY2']	= "opnameprojectmoving_line";
	
	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>