<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   igunrn    created date 08/11/2011 13:21
Opname Project
Filename: uitrnopnameproject-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->opnameproject_startdate = $__POSTDATA->H->opnameproject_startdate;
			$obj->opnameproject_enddate = $__POSTDATA->H->opnameproject_enddate;
			$obj->opnameproject_isdisabled = $__POSTDATA->H->opnameproject_isdisabled;
			$obj->opnameproject_descr = $__POSTDATA->H->opnameproject_descr;
			$obj->opnameproject_createby = $__POSTDATA->H->opnameproject_createby;
			$obj->opnameproject_createdate = $__POSTDATA->H->opnameproject_createdate;
			$obj->opnameproject_modifyby = $__POSTDATA->H->opnameproject_modifyby;
			$obj->opnameproject_modifydate = $__POSTDATA->H->opnameproject_modifydate;
			$obj->opnameproject_isposted = $__POSTDATA->H->opnameproject_isposted;
			$obj->opnameproject_isgenerated = $__POSTDATA->H->opnameproject_isgenerated;
			$obj->region_id = $__POSTDATA->H->region_id;
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
		
	
			function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;
			$channel_number = '05';	 
			$sql  =  "DECLARE @id as varchar(50);";
			$sql .=  "EXEC cp_sequencer_opname 'OP', @id OUTPUT ";
			$rs   = $conn->Execute($sql);
			
			$id = $rs->fields['id'];
			
			if ($id) {
				return $id;
			} else {
				return $time();
			}
			
			
		}		

?>