<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   dwi.atnorn    created date 01/07/2011 11:11
customer traffic
Filename: uimstsalesperson-savecheck.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}
	$username 	= $_SESSION["username"];
	$__ID		= $_POST['__ID'];
	$__NAME		= $_POST['__NAME'];
		
	unset($data);
	
	
	set_time_limit(100);
	$failed = 0;


	$sql = "select * from master_season where season_id='$__ID'"; 

	$rs  = $conn->Execute($sql);

	
	$season_id = $rs->fields['$__ID'];
	$totalCount = $rs->recordCount();
	

 
if ($totalCount>0)
{
	  		
	$failed    = 1;
	$POSTMSG   = 'ID Duplicated, Data cannot be saved';
				
}
else
{



 	$sql = "select * from master_season where season_name='$__NAME'"; 
	$rs  = $conn->Execute($sql);

	$totalCount = $rs->recordCount();

 	if ($totalCount==0)	
	{			$failed = 0;
				$POSTMSG   = "BOLEH";
	}		
	else
	{
				$failed    = 1;
				$POSTMSG   = 'NAME Duplicated, Data cannot be saved';
	}			 
}
  
 
			unset($obj);
			$obj->failed  	= $failed;
			$obj->message 	= $POSTMSG;
			$data = array($obj);	
				

				
$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
 
print(stripslashes(json_encode($objResult)));


?>