<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   fakhri.reza
    created date 21/05/2012 09:10
Master Season
Filename: uimstseason-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->season_id = $__POSTDATA->H->season_id;
			$obj->season_name = $__POSTDATA->H->season_name;
			$obj->season_namealias = $__POSTDATA->H->season_namealias;
			$obj->season_datestart = $__POSTDATA->H->season_datestart;
			$obj->season_dateend = $__POSTDATA->H->season_dateend;
			$obj->season_isvisible_datestart = $__POSTDATA->H->season_isvisible_datestart;
			$obj->season_isvisible_dateend = $__POSTDATA->H->season_isvisible_dateend;
			$obj->season_isclosed = $__POSTDATA->H->season_isclosed;
			$obj->season_createby = $__POSTDATA->H->season_createby;
			$obj->season_createdate = $__POSTDATA->H->season_createdate;
			$obj->season_modifyby = $__POSTDATA->H->season_modifyby;
			$obj->season_modifydate = $__POSTDATA->H->season_modifydate;
			$obj->season_closeby = $__POSTDATA->H->season_closeby;
			$obj->season_closedate = $__POSTDATA->H->season_closedate;
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-headermanualid.inc.php';
		}
		
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];

			if ($id) {
				return $id;
			} else {
				return $__POSTDATA->H->season_id;
			}
		}		
	

?>