<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   fakhri.reza
    created date 21/05/2012 09:10
Master Season
Filename: uimstseason.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'master_season';
	$__CONF['H']['PRIMARY_KEY'] 				= 'season_id';
	$__CONF['H']['CREATEBY'] 					= 'season_createby';
	$__CONF['H']['CREATEDATE'] 					= 'season_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'season_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'season_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>