<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 10/05/2011 15:24
asset category
Filename: uimstassetctg-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from master_assetctg where assetctg_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->assetctg_id = trim($rs->fields['assetctg_id']);
	$objh->assetctg_name = trim($rs->fields['assetctg_name']);
	$objh->assetctg_descr = trim($rs->fields['assetctg_descr']);
	$objh->assetctg_isdisabled = trim($rs->fields['assetctg_isdisabled']);
	$objh->assetctg_createby = trim($rs->fields['assetctg_createby']);
	$objh->assetctg_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetctg_createdate']));
	$objh->assetctg_modifyby = trim($rs->fields['assetctg_modifyby']);
	$objh->assetctg_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetctg_modifydate']));
	$objh->assetgro_id = trim($rs->fields['assetgro_id']);
	$objh->rowid = trim($rs->fields['rowid']);

	/* Lookup data Header */
	$data[0]['H'] = $objh;

	$sql = "
	
select * from master_assetctgstrukturunit A
inner join master_strukturunit B 
ON A.strukturunit_id = B.strukturunit_id WHERE
A.assetctg_id = '$id'";


	$rsstruk=$conn->execute ($sql);	

	unset($arrdata);
	$arrdata = array();
	while (!$rsstruk->EOF)
	{
				unset($obj);	
				$obj->strukturunit_id = trim($rsstruk->fields['strukturunit_id']);
				$obj->strukturunit_name = trim($rsstruk->fields['strukturunit_name']);
	
				$arrdata[] = $obj;
	 			$rsstruk->MoveNext();
	 }
	 

	$data[0]['D']['strukturunit'] = $arrdata;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>