<?
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 10/05/2011 15:24
asset category
Filename: uimstassetctg-gridlistload.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}


	/* Default Criteria */
	
/*	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_txt_assetctg_id', 'assetctg_id', "refParser ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_txt_assetctg_name', 'assetctg_name', "{db_field} LIKE '%{criteria_value}%'");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_cmb_assetgro_id', 'assetgro_id', "refParser");
*/

	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetctg_id', 'assetctg_id', "refParser");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetctg_name', 'assetctg_name', "{db_field} LIKE '%{criteria_value}%'");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetgro_id', 'assetgro_id', "refParser");
	
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM master_assetctg WHERE $SQL_CRITERIA ORDER BY assetctg_id DESC";
} else {
	$sql = "SELECT * FROM master_assetctg ORDER BY assetctg_id DESC";
}



$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);
	$obj->assetctg_id = trim($rs->fields['assetctg_id']);
	$obj->assetctg_name = trim($rs->fields['assetctg_name']);
	$obj->assetctg_descr = trim($rs->fields['assetctg_descr']);
	$obj->assetctg_isdisabled = trim($rs->fields['assetctg_isdisabled']);
	$obj->assetgro_id = trim($rsCTG->fields['assetgro_id']);
	
	
	$assetgro_id = trim($rs->fields['assetgro_id']);
	$SQLCTG="SELECT assetgro_name FROM master_assetgro WHERE assetgro_id = '$assetgro_id'";
	$rsCTG=$conn->execute($SQLCTG);
	
	$obj->assetgro_name = trim($rsCTG->fields['assetgro_name']);

 

	$data[] = $obj;
	$rs->MoveNext();
}



$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>