<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 10/05/2011 15:24
asset category
Filename: uimstassetctg-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->assetctg_name = $__POSTDATA->H->assetctg_name;
			$obj->assetctg_descr = $__POSTDATA->H->assetctg_descr;
			$obj->assetctg_isdisabled = $__POSTDATA->H->assetctg_isdisabled;
			$obj->assetctg_createby = $__POSTDATA->H->assetctg_createby;
			$obj->assetctg_createdate = $__POSTDATA->H->assetctg_createdate;
			$obj->assetctg_modifyby = $__POSTDATA->H->assetctg_modifyby;
			$obj->assetctg_modifydate = $__POSTDATA->H->assetctg_modifydate;
			$obj->assetgro_id = $__POSTDATA->H->assetgro_id;
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
		
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];

			if ($id) {
				return $id;
			} else {
				return $prefix.time();
			}
		}		
	

?>