<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 10/05/2011 09:21
Asset Class
Filename: uimstassetclass-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->assetclass_seq = $__POSTDATA->H->assetclass_seq;
			$obj->assetclass_name = $__POSTDATA->H->assetclass_name;
			$obj->assetclass_descr = $__POSTDATA->H->assetclass_descr;
			$obj->assetclass_isdisabled = $__POSTDATA->H->assetclass_isdisabled;
			$obj->assetclass_createby = $__POSTDATA->H->assetclass_createby;
			$obj->assetclass_createdate = $__POSTDATA->H->assetclass_createdate;
			$obj->assetclass_modifyby = $__POSTDATA->H->assetclass_modifyby;
			$obj->assetclass_modifydate = $__POSTDATA->H->assetclass_modifydate;
			$obj->assetgro_id = $__POSTDATA->H->assetgro_id;
			$obj->assetctg_id = $__POSTDATA->H->assetctg_id;
		
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
		}
		
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];

			if ($id) {
				return $id;
			} else {
				return $prefix.time();
			}
		}		
	

?>