<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 10/05/2011 09:21
Asset Class
Filename: uimstassetclass.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'master_assetclass';
	$__CONF['H']['PRIMARY_KEY'] 				= 'assetclass_id';
	$__CONF['H']['CREATEBY'] 					= 'assetclass_createby';
	$__CONF['H']['CREATEDATE'] 					= 'assetclass_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'assetclass_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'assetclass_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>