<?
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 10/05/2011 09:21
Asset Class
Filename: uimstassetclass-gridlistload.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}


	/* Default Criteria */
	/*
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_channel_id', 'channel_id', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " %s = '%s' ");
	*/

	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetclass_id', 'assetclass_id', "refParser");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetclass_name', 'assetclass_name', "{db_field} LIKE '%{criteria_value}%'");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetgro_id', 'assetgro_id', "refParser");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_assetctg_id', 'assetctg_id', "refParser");
	
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM master_assetclass WHERE $SQL_CRITERIA ORDER BY assetclass_id DESC";
} else {
	$sql = "SELECT * FROM master_assetclass ORDER BY assetclass_id DESC";
}



$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);
	$obj->assetclass_id = trim($rs->fields['assetclass_id']);
	$obj->assetclass_seq = (float) trim($rs->fields['assetclass_seq']);
	$obj->assetclass_name = trim($rs->fields['assetclass_name']);
	$obj->assetclass_descr = trim($rs->fields['assetclass_descr']);
	$obj->assetclass_isdisabled = trim($rs->fields['assetclass_isdisabled']);
	$obj->assetclass_createby = trim($rs->fields['assetclass_createby']);
	$obj->assetclass_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetclass_createdate']));
	$obj->assetclass_modifyby = trim($rs->fields['assetclass_modifyby']);
	$obj->assetclass_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['assetclass_modifydate']));
	$obj->assetgro_id = trim($rs->fields['assetgro_id']);
	$obj->assetctg_id = trim($rs->fields['assetctg_id']);
	$obj->rowid = trim($rs->fields['rowid']);

	$data[] = $obj;
	$rs->MoveNext();
}



$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>