<?
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   dwi.atnorn    created date 01/07/2011 11:11
customer traffic
Filename: uitrncusttraffic-gridlistload.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}


	/* Default Criteria */
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_branch_id', 'branch_id'," %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_custtraffic_id', 'custtraffic_id', "{db_field} LIKE '%{criteria_value}%'");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_isPosted', 'custtraffic_isposted', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_custtraffic_date', 'custtraffic_date', " convert(varchar(10),custtraffic_date,120) =convert(varchar(10), '{criteria_value}',120) ");
	//SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_hemoving_dateend', 'hemoving_date_fr', " convert(varchar(10),hemoving_date_fr,120)<=convert(varchar(10),'{criteria_value}',120) ");
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM transaksi_custtraffic WHERE $SQL_CRITERIA ORDER BY custtraffic_id DESC";
} else {
	$sql = "SELECT * FROM transaksi_custtraffic ORDER BY custtraffic_id DESC";
}


 
$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);

	
	$obj->custtraffic_id = trim($rs->fields['custtraffic_id']);
	$obj->custtraffic_date 			= SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['custtraffic_date']));
	$obj->custtraffic_modifyby = trim($rs->fields['custtraffic_modifyby']);
	$obj->custtraffic_modifydate 	= SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['custtraffic_modifydate']));
	$obj->custtraffic_createby = trim($rs->fields['custtraffic_createby']);
	$obj->custtraffic_createdate 	= SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['custtraffic_createdate']));
	
	$region_id 				= 	trim($rs->fields['region_id']);
    $SQLB					= "SELECT region_name FROM master_region WHERE region_id = '$region_id'";
    $rsB 					= $conn->execute($SQLB);
	$region_name 			= 	trim($rsB->fields['region_name']);
	$obj->region_id			=	$region_name;
	
	$branch_id 				= 	trim($rs->fields['branch_id']);
    $SQLC					= "SELECT branch_name FROM master_branch WHERE branch_id = '$branch_id'";
    $rsC 					= $conn->execute($SQLC);
	$branch_name 			= 	trim($rsC->fields['branch_name']);
	$obj->branch_id			=	$branch_name;
	
	$obj->custtraffic_isposted = 1*$rs->fields['custtraffic_isposted'];
	$obj->rowid = trim($rs->fields['rowid']);

	$data[] = $obj;
	$rs->MoveNext();
}



$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>