<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   dwi.atnorn    created date 01/07/2011 11:11
customer traffic
Filename: uitrncusttraffic-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from transaksi_custtraffic where custtraffic_id='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->custtraffic_id = trim($rs->fields['custtraffic_id']);
	$objh->custtraffic_date = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['custtraffic_date']));
	$objh->custtraffic_isposted = trim($rs->fields['custtraffic_isposted']);
	$objh->custtraffic_modifyby = trim($rs->fields['custtraffic_modifyby']);
	$objh->custtraffic_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['custtraffic_modifydate']));
	$objh->custtraffic_createby = trim($rs->fields['custtraffic_createby']);
	$objh->custtraffic_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['custtraffic_createdate']));
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->branch_id = trim($rs->fields['branch_id']);
	$objh->rowid = trim($rs->fields['rowid']);



	$sql = "select * from transaksi_custtrafficdetil where custtraffic_id='$id'";
	$rs  = $conn->Execute($sql);
	$arrdata = array();
	while (!$rs->EOF) {
		unset($obj);
		$obj->custtraffic_id = trim($rs->fields['custtraffic_id']);
		$obj->custtrafficdetil_line = (float) trim($rs->fields['custtrafficdetil_line']);
		$obj->custtrafficdetil_waktu = trim($rs->fields['custtrafficdetil_waktu']);
		$obj->custtrafficdetil_W = (float) trim($rs->fields['custtrafficdetil_W']);
		$obj->custtrafficdetil_I = (float) trim($rs->fields['custtrafficdetil_I']);
		$obj->custtrafficdetil_P = (float) trim($rs->fields['custtrafficdetil_P']);
		$obj->rowid = trim($rs->fields['rowid']);

		$arrdata[] = $obj;
		$rs->MoveNext();
	}
	$data[0]['D']['transaksi_custtrafficdetil'] = $arrdata;
	
	
	
	
	
	
	
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>