<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   dwi.atnorn    created date 01/07/2011 11:11
customer traffic
Filename: uitrncusttraffic.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'transaksi_custtraffic';
	$__CONF['H']['PRIMARY_KEY'] 				= 'custtraffic_id';
	$__CONF['H']['CREATEBY'] 					= 'custtraffic_createby';
	$__CONF['H']['CREATEDATE'] 					= 'custtraffic_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'custtraffic_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'custtraffic_modifydate';

	$__CONF['D']['transaksi_custtrafficdetil']['TABLE_NAME']		= "transaksi_custtrafficdetil";
	$__CONF['D']['transaksi_custtrafficdetil']['PRIMARY_KEY1']	= "custtraffic_id";
	$__CONF['D']['transaksi_custtrafficdetil']['PRIMARY_KEY2']	= "custtrafficdetil_line";
	
	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>