<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   fakhri.rezarn    created date 14/09/2012 13:52
Program Persetujuan Orientasi
Filename: uimstapporientation.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'master_employee';
	$__CONF['H']['PRIMARY_KEY'] 				= 'employee_contractno';
	$__CONF['H']['CREATEBY'] 					= 'employee_createby';
	$__CONF['H']['CREATEDATE'] 					= 'employee_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'employee_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'employee_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>