<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   fakhri.rezarn    created date 14/09/2012 13:52
Program Persetujuan Orientasi
Filename: uimstapporientation-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			
			$obj->employee_contractno = $__POSTDATA->H->employee_contractno;
			$obj->employee_nik		=	$__POSTDATA->H->employee_nik;
			$obj->employee_pihak1name = $__POSTDATA->H->employee_pihak1name;
			$obj->employee_pihak2name = $__POSTDATA->H->employee_pihak2name;
			$obj->employee_pihak1jabatan = $__POSTDATA->H->employee_pihak1jabatan;
			$obj->jabatan_id = $__POSTDATA->H->jabatan_id;
			$obj->jabatan_name = $__POSTDATA->H->jabatan_name;
			$obj->employee_pihak2address = $__POSTDATA->H->employee_pihak2address;
			$obj->employee_kontrak = $__POSTDATA->H->employee_kontrak;
			$obj->employee_startdate = $__POSTDATA->H->employee_startdate;
			$obj->employee_enddate = $__POSTDATA->H->employee_enddate;
			$obj->employee_pihak2location = $__POSTDATA->H->employee_pihak2location;
			$obj->employee_tipekontrak = $__POSTDATA->H->employee_tipekontrak;
			$obj->employee_gapok = $__POSTDATA->H->employee_gapok;
			$obj->employee_tunj_jabatan = $__POSTDATA->H->employee_tunj_jabatan;
			$obj->employee_tunj_telkom = $__POSTDATA->H->employee_tunj_telkom;
			$obj->employee_tunj_transport = $__POSTDATA->H->employee_tunj_transport;
			$obj->employee_tunj_harian = $__POSTDATA->H->employee_tunj_harian;
			$obj->employee_intensif_longshift = $__POSTDATA->H->employee_intensif_longshift;
			$obj->employee_createby = $__POSTDATA->H->employee_createby;
			$obj->employee_createdate = $__POSTDATA->H->employee_createdate;
			$obj->employee_modifyby = $__POSTDATA->H->employee_modifyby;
			$obj->employee_modifydate = $__POSTDATA->H->employee_modifydate;
			$obj->employee_isdisabled = $__POSTDATA->H->employee_isdisabled;
			$obj->region_id = $__POSTDATA->H->region_id;
			/*
			$obj->employee_isdisabled = $__POSTDATA->H->employee_isdisabled;
			$region_id = trim($rs->fields['region_id']);
			$SQLC					= 	"SELECT region_name FROM master_region WHERE region_id = '$region_id'";
			$rsC 					= 	$conn->execute($SQLC);
			$region_name 			= 	trim($rsC->fields['region_name']);
			$obj->region_id			=	$region_id;
			$obj->region_name		=	$region_name;
			*/
			
			

			
				$_MODIFIED = true; 
				
			if ($obj->employee_tipekontrak=='TRAINING')
			{
				$_ID_GENERATOR_ARGS = array(
					'prefix' 	=> 'TRN',
					'channel_id' 	=> 'TFI',
					'departemen_id'  => '1000600'
				);
			}
			elseif ($obj->employee_tipekontrak=='TEMPORER')
			{	
				$_ID_GENERATOR_ARGS = array(
					'prefix' 	=> 'TMP',
					'channel_id' 	=> 'TFI',
					'departemen_id'  => '1000600'
				);
			}
			elseif ($obj->employee_tipekontrak=='KONTRAK 1')
			{
				$_ID_GENERATOR_ARGS = array(
					'prefix' 	=> 'KT1',
					'channel_id' 	=> 'TFI',
					'departemen_id'  => '1000600'
				);
			}
			elseif ($obj->employee_tipekontrak=='KONTRAK 2')
			{
				$_ID_GENERATOR_ARGS = array(
					'prefix' 	=> 'KT2',
					'channel_id' 	=> 'TFI',
					'departemen_id'  => '1000600'
				);
			}	
			elseif ($obj->employee_tipekontrak=='PENSIUN')
			{
				$_ID_GENERATOR_ARGS = array(
					'prefix' 	=> 'PSN',
					'channel_id' 	=> 'TFI',
					'departemen_id'  => '1000600'
				);
			}
				require dirname(__FILE__).'/../../../../updatedefault-header.inc.php';
			
		}
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;
		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];		
			$channel_id = $_ID_GENERATOR_ARGS['channel_id'];
			$departemen_id = $_ID_GENERATOR_ARGS['departemen_id'];

			
			$sql  =		"DECLARE @id as varchar(32)";
			$sql .=  	"EXEC sp_sequencer_orientation 'TFI','$prefix','1000600',@id OUTPUT ";
			$rs   = 	$conn->Execute($sql);
			$id   =		$rs->fields['id'];
		
		
		//$id = "12/TRN/TFI/HR/0001";
		
			if ($id) {
				return $id;
			} else {
				return $prefix.time();
			}
		}		
	

?>