<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --rn    created by   fakhri.rezarn    created date 14/09/2012 13:52
Program Persetujuan Orientasi
Filename: uimstapporientation-open.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

	$username 	= $_SESSION["username"];
	$id 		= $_POST['id'];
	
	
	unset($data);
	
	set_time_limit(100);


	$sql = "select * from master_employee where employee_contractno='$id'";
	$rs  = $conn->Execute($sql);
	unset($objh);
	$objh->employee_contractno = trim($rs->fields['employee_contractno']);
	$objh->employee_nik = trim($rs->fields['employee_nik']);
	$objh->employee_pihak1name = trim($rs->fields['employee_pihak1name']);
	$objh->employee_pihak2name = trim($rs->fields['employee_pihak2name']);
	$objh->employee_pihak1jabatan = trim($rs->fields['employee_pihak1jabatan']);
	$objh->jabatan_id = trim($rs->fields['jabatan_id']);
	$objh->jabatan_name = trim($rs->fields['jabatan_name']);
	$objh->employee_pihak2address = trim($rs->fields['employee_pihak2address']);
	$objh->employee_kontrak = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['employee_kontrak']));
	$objh->employee_startdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['employee_startdate']));
	$objh->employee_enddate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['employee_enddate']));
	$objh->employee_pihak2location = trim($rs->fields['employee_pihak2location']);
	$objh->employee_tipekontrak = trim($rs->fields['employee_tipekontrak']);
	$objh->employee_gapok = trim($rs->fields['employee_gapok']);
	$objh->employee_tunj_jabatan = trim($rs->fields['employee_tunj_jabatan']);
	$objh->employee_tunj_telkom = trim($rs->fields['employee_tunj_telkom']);
	$objh->employee_tunj_transport = trim($rs->fields['employee_tunj_transport']);
	$objh->employee_tunj_harian = trim($rs->fields['employee_tunj_harian']);
	$objh->employee_intensif_longshift = trim($rs->fields['employee_intensif_longshift']);
	$objh->employee_createby = trim($rs->fields['employee_createby']);
	$objh->employee_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['employee_createdate']));
	$objh->employee_modifyby = trim($rs->fields['employee_modifyby']);
	$objh->employee_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['employee_modifydate']));
	$objh->employee_isdisabled = trim($rs->fields['employee_isdisabled']);
/*
	$region_id = trim($rs->fields['region_id']);
	$SQLC					= 	"SELECT region_name FROM master_region WHERE region_id = '$region_id'";
	$rsC 					= 	$conn->execute($SQLC);
	$region_name 			= 	trim($rsC->fields['region_name']);
	$objh->region_id		=	$region_id;
	$objh->region_name		=	$region_name;
*/
	$objh->region_id = trim($rs->fields['region_id']);
	$objh->region_name = trim($rs->fields['region_name']);
	$objh->rowid = trim($rs->fields['rowid']);



	
	
	
	
	
	
	
	

	/* Lookup data Header */
	$data[0]['H'] = $objh;




/* ====================================================================================================== */
$sql = "select * from transaksi_tprop where id='$id'";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->id = trim($rs->fields['id']);
	$obj->prop_line = 1*$rs->fields['prop_line'];
	$obj->prop_name = $rs->fields['prop_name'];
	$obj->prop_descr = $rs->fields['prop_descr'];
	$obj->prop_value = $rs->fields['prop_value'];
	$obj->rowid = $rs->fields['rowid'];	
	$arrdata[] = $obj;
	$rs->MoveNext();
}
$data[0]['D']['Prop'] = $arrdata;


$i = 1;
$sql = "select * from transaksi_tlog where id='$id'  ";
$rs  = $conn->Execute($sql);
unset($arrdata);
$arrdata = array();
while (!$rs->EOF) {
	unset($obj);
	$obj->log_id = trim($rs->fields['id']);
	$obj->log_line =  $i; //$rs->fields['log_line'];
	$obj->log_date = trim($rs->fields['log_date']);
	$obj->log_action = $rs->fields['log_action'];
	$obj->log_descr = $rs->fields['log_descr'];
	$obj->log_table = $rs->fields['log_table'];
	$obj->log_lastvalue = $rs->fields['log_lastvalue'];
	$obj->log_username = $rs->fields['log_username'];
	$obj->rowid = $rs->fields['rowid'];
	$arrdata[] = $obj;
	$rs->MoveNext();
	$i++;
}
$data[0]['D']['Log'] = $arrdata;




$objResult = new WebResultObject("objResult");
$objResult->totalCount = 1;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>