<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 04/05/2011 15:56
inv tester
Filename: uimstctg.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'master_heinvctg';
	$__CONF['H']['PRIMARY_KEY'] 				= 'heinvctg_id';
	$__CONF['H']['CREATEBY'] 					= 'heinvctg_createby';
	$__CONF['H']['CREATEDATE'] 					= 'heinvctg_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'heinvctg_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'heinvctg_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>