<?
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   dwi.atno
    created date 04/05/2011 15:56
inv tester
Filename: uimstctg-gridlistload.php
*/



if (!defined('__SERVICE__')) {
	die("access denied");
}

$username 	= $_SESSION["username"];
$limit 		= $_POST['limit'];
$start 		= $_POST['start'];
$criteria	= $_POST['criteria'];

$SQL_CRITERIA = "";
$objCriteria = json_decode(stripslashes($criteria));
if (is_array($objCriteria)) {
	$criteria = array();
	while (list($name, $value) = each($objCriteria)) {
		$criteria[$value->name] = $value;
		//seharusnya amankan criteria di sini, cegat di $criteria[$value->name]->value
	}


	/* Default Criteria */
	/*
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_channel_id', 'channel_id', " %s = '%s' ");
	
	*/

	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_heinvctg_id', 'heinvctg_id', "refParser");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_region_id', 'region_id', " %s = '%s' ");
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_heinvgro_id', 'heinvgro_id', " %s = '%s' ");	
	SQLUTIL::BuildCriteria(&$SQL_CRITERIA, $criteria, 'obj_search_chk_heinvctg_name', 'heinvctg_name', " {db_field} LIKE '%{criteria_value}%'");
	
}


if ($SQL_CRITERIA) {
	$sql = "SELECT * FROM master_heinvctg WHERE $SQL_CRITERIA ORDER BY heinvctg_id DESC";
} else {
	$sql = "SELECT * FROM master_heinvctg ORDER BY heinvctg_id DESC";
}



$rs = $conn->Execute($sql);
$totalCount = $rs->recordCount();
$rs = $conn->SelectLimit($sql, $limit, $start);
$data = array();
while (!$rs->EOF) {

	unset($obj);
	$obj->heinvctg_id = trim($rs->fields['heinvctg_id']);
	$obj->heinvctg_extctg = trim($rs->fields['heinvctg_extctg']);
	$obj->heinvctg_extgro = trim($rs->fields['heinvctg_extgro']);
	$obj->heinvctg_seqcode = trim($rs->fields['heinvctg_seqcode']);
	$obj->heinvctg_name = trim($rs->fields['heinvctg_name']);
	$obj->heinvctg_namegroup = trim($rs->fields['heinvctg_namegroup']);
	$obj->heinvctg_descr = trim($rs->fields['heinvctg_descr']);
	$obj->heinvctg_sizetag = trim($rs->fields['heinvctg_sizetag']);
	$obj->heinvctg_isdisabled = trim($rs->fields['heinvctg_isdisabled']);
	$obj->heinvctg_createby = trim($rs->fields['heinvctg_createby']);
	$obj->heinvctg_createdate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['heinvctg_createdate']));
	$obj->heinvctg_modifyby = trim($rs->fields['heinvctg_modifyby']);
	$obj->heinvctg_modifydate = SQLUTIL::SQLDateParseToStringdatesmall(trim($rs->fields['heinvctg_modifydate']));
	$heinvgro_id = trim($rs->fields['heinvgro_id']);
	$SQLC					= 	"SELECT heinvgro_name FROM master_heinvgro WHERE heinvgro_id = '$heinvgro_id'";
	$rsC 					= 	$conn->execute($SQLC);
	$heinvgro_name 			= 	trim($rsC->fields['heinvgro_name']);
	$obj->heinvgro_id			=	$heinvgro_id;
	$obj->heinvgro_name			=	$heinvgro_name;
	$obj->region_id = trim($rs->fields['region_id']);
	$obj->rowid = trim($rs->fields['rowid']);

	$data[] = $obj;
	$rs->MoveNext();
}
		


$objResult = new WebResultObject("objResult");
$objResult->totalCount = $totalCount;
$objResult->success = true;
$objResult->data = $data;
unset($objResult->errors); 
		
print(stripslashes(json_encode($objResult)));

?>