<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   fakhri.reza
    created date 21/05/2012 13:21
POS Sales Person
Filename: uimstsalesperson.inc.php
*/




	$__CONF['H']['TABLE_NAME'] 					= 'master_possalesperson';
	$__CONF['H']['PRIMARY_KEY'] 				= 'possalesperson_id';
	$__CONF['H']['CREATEBY'] 					= 'possalesperson_createby';
	$__CONF['H']['CREATEDATE'] 					= 'possalesperson_createdate';
	$__CONF['H']['MODIFYBY'] 					= 'possalesperson_modifyby';
	$__CONF['H']['MODIFYDATE'] 					= 'possalesperson_modifydate';

	
	$__CONF['D']['Prop']['TABLE_NAME']			= "transaksi_tprop";
	$__CONF['D']['Prop']['PRIMARY_KEY1']		= "id";
	$__CONF['D']['Prop']['PRIMARY_KEY2']		= "prop_line";	

	$__CONF['D']['Log']['TABLE_NAME']			= "transaksi_tlog";
	$__CONF['D']['Log']['PRIMARY_KEY1']			= "id";
	$__CONF['D']['Log']['PRIMARY_KEY2']			= "log_line";	



?>