<?php
/*
Generated by TransBrowser Generator
*** Genearated by TransBrowser UI Application Generator --
    created by   fakhri.reza
    created date 21/05/2012 13:21
POS Sales Person
Filename: uimstsalesperson-save_header.php
*/

	

		/* Update Header */
		if (!empty($__POSTDATA->H)) {
		
			unset($obj);
			$obj->possalesperson_id = $__POSTDATA->H->possalesperson_id;
			$obj->possalesperson_name = $__POSTDATA->H->possalesperson_name;
			$obj->possalesperson_isdisabled = $__POSTDATA->H->possalesperson_isdisabled;
			$obj->region_id = $__POSTDATA->H->region_id;
			$obj->nik = $__POSTDATA->H->nik;
			/*
			$obj->possalesperson_createby = $__POSTDATA->H->possalesperson_createby;
			$obj->possalesperson_createdate = $__POSTDATA->H->possalesperson_createdate;
			$obj->possalesperson_modifyby = $__POSTDATA->H->possalesperson_modifyby;
			$obj->possalesperson_modifydate = $__POSTDATA->H->possalesperson_modifydate;
			*/
			$_MODIFIED = true; 
			$_ID_GENERATOR_ARGS = array(
				'prefix' 	=> ''
			);
			require dirname(__FILE__).'/../../../../updatedefault-headermanualid.inc.php';
		}
		
		function GenerateID($_ID_GENERATOR_ARGS) {
			global $conn;		
			$prefix = $_ID_GENERATOR_ARGS['prefix'];

			if ($id) {
				return $id;
			} else {
				return $__POSTDATA->H->possalesperson_id;
			}
		}		
	

?>